from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FRONTEND_SOURCE = ROOT / 'frontend' / 'src' / 'main.tsx'
FRONTEND_DIST = ROOT / 'frontend' / 'dist'


def frontend_source() -> str:
    return FRONTEND_SOURCE.read_text()


def frontend_bundle() -> str:
    assets = sorted((FRONTEND_DIST / 'assets').glob('index-*.js'))
    assert assets, 'frontend/dist does not include the built ESP index bundle'
    return '\n'.join(asset.read_text() for asset in assets)


def assert_campaign_next_step_contract(source: str) -> None:
    expected_tokens = [
        'const campaignNextStep = !workflowStatus',
        "label: 'Run readiness'",
        "actionLabel: 'Refresh Readiness'",
        "label: 'Fix validation blockers'",
        "actionLabel: 'Check Audience'",
        "label: 'Preview test content'",
        "actionLabel: 'Preview Email'",
        "label: 'Dry-run launch'",
        "actionLabel: 'Dry-Run Launch'",
        'Guided next step',
        'campaignNextStep.detail',
        'campaignNextStep.run',
        'campaignTriageAction',
        'campaignTriageItems',
        "title: 'Create campaign draft'",
        "title: 'Choose template'",
        "title: 'Choose audience'",
        "title: 'Run readiness'",
        "title: 'Fix validation blockers'",
        "title: 'Send proof email'",
        "title: 'Dry-run launch'",
        "title: 'Monitor delivery'",
        "title: 'Campaign ready'",
        'Campaign triage',
        'Draft',
        'Content',
        'Audience',
        'Readiness',
        'Proof and launch',
        'launchFoundationItems',
        'Launch Foundations',
        'Template contract, audience snapshot, send engine handoff, and suppression impact.',
        'Template contract',
        'Select a saved template before proof or launch.',
        'Audience snapshot',
        'Choose an audience so launch volume and suppressions can be checked.',
        'Send engine handoff',
        'Run dry-run launch before production queueing.',
        'Suppression impact',
        'Dry-run to reveal opt-out, bounce, and complaint suppression impact.',
        'campaign-foundation-panel',
        'campaign-foundation-strip',
        'campaign-foundation-item',
        'campaign-triage-panel',
        'campaign-triage-list',
        'campaign-triage-row',
        'aiCampaignSummary',
        'aiCampaignRecommendations',
        'reviewCampaignWithAi',
        "fetchJson<AIWorkflowAnalysis>('/api/v1/ai/campaigns/analyze'",
        'AI Campaign Review',
        'campaign-ai-review-panel',
        'campaign-ai-summary',
        'Run AI Campaign Review after loading readiness',
        'type CampaignLaunchResult',
        'type CampaignTestSendResult',
        'lastLaunchResult',
        'lastTestSendResult',
        'latest_proof_route',
        'latestProofRouteDetail',
        'latestProofRouteEvidence',
        'latest_proof_route_evidence',
        'latestProofRouteOk',
        'proofRouteAvailable',
        'activeProofRouteDetail',
        'Latest proof route',
        'delivery_route_mode',
        'route_mode_provider',
        'submission_provider',
        "latestProofRoute.mta_route_decision_basis ? latestProofRoute.mta_route_decision_basis.replace",
        'latestProofRoute.mta_rule_hit_name || latestProofRoute.mta_routing_rule_name',
        'latestProofRoute.mta_rule_hit_source || latestProofRoute.mta_routing_rule_source',
        'pool source ${latestProofRoute.mta_ip_pool_selection_source}',
        'providers ${latestProofRoute.mta_rule_hit_provider_preference.join',
        'providers ${latestProofRoute.mta_preferred_providers.join',
        'fallback used',
        'fallback ${latestProofRoute.mta_provider_preference_fallback_provider}',
        'node ${latestProofRoute.mta_node_name}',
        'pool ${latestProofRoute.mta_ip_pool_name}',
        'capacity ${latestProofRoute.mta_pool_capacity_status}',
        'rate ${latestProofRoute.mta_rate_limit_recent_count',
        'block ${latestProofRoute.mta_route_block_code}',
        'issue ${latestProofRoute.mta_route_block_message}',
        "latestProofRoute.mta_submission_host ? `${latestProofRoute.mta_submission_host}:${latestProofRoute.mta_submission_port",
        'latestProofRoute.mta_public_ipv4',
        'decision_basis',
        'provider_fallback_available',
        'capacity_status',
        'block_code',
        'Mode',
        'Refresh readiness after proof send to load persisted route evidence.',
        'setLastTestSendResult({ ...data, to_email: formText(testEmail) })',
        'setLastLaunchResult(data)',
        'Dry-run result',
        'Launch result',
        'Test send result',
        'test-send-result-card',
        'mta_hostname',
        'mta_ip_pool_name',
        'mta_ip_pool_selection_source',
        'mta_route_decision_basis',
        'mta_routing_rule_name',
        'mta_routing_rule_source',
        'mta_preferred_providers',
        'mta_rule_hit_name',
        'mta_rule_hit_pool_source',
        'mta_rule_hit_provider_preference',
        'mta_rule_hit_provider_preference_mode',
        'mta_provider_preference_fallback_used',
        'Rule hit',
        'Rule inputs',
        'mta_node_selection_membership_id',
        'mta_node_candidate_count',
        'mta_node_selection_priority',
        'mta_node_selection_weight',
        'mta_node_skipped_count',
        'mta_node_skipped_nodes',
        'mta_provider_preference_blocked',
        'mta_provider_preference_fallback_available',
        'mta_provider_preference_fallback_provider',
        'mta_provider_preference_fallback_node_name',
        'mta_pool_available_node_count',
        'mta_pool_required_available_node_count',
        'mta_pool_capacity_status',
        'mta_rate_limit_scope',
        'mta_rate_limit_window_seconds',
        'mta_rate_limit_max_per_minute',
        'mta_rate_limit_recent_count',
        'smtp_response_code',
        'mta_route_block_code',
        'delivery_error_message',
        'proofSendRouteLabel',
        'proofSendSummary',
        'proofSendOk',
        'canDryRunLaunch',
        'proofAuditTarget',
        'proofRoutingBlockerMessage',
        'operationNeedsProofRouting',
        'throw new Error(proofRoutingBlockerMessage)',
        'Resolve proof routing before dry-run launch.',
        'Open Delivery audit',
        'Proof blocked',
        'Resolve proof routing',
        'Proof send did not complete with a clean delivery handoff.',
        'route ${lastTestSendResult.mta_route_status}',
        '<span>Route</span>',
        'mta_route_status',
        '<span>Route status</span>',
        '<span>Decision</span>',
        '<span>Rule</span>',
        '<span>Candidates</span>',
        'send_record_status',
        'send_job_status',
        'mta_submission_host',
        'mta_submission_port',
        'envelope_from',
        'dkim_selector',
        'delivery_attempt_id',
        '#delivery/${lastTestSendResult.send_record_id}',
        '/${lastTestSendResult.delivery_attempt_id}',
        'lastLaunchResult.requested_count',
        'lastLaunchResult.queued_count',
        'lastLaunchResult.suppressed_count',
        'launch-result-card',
    ]

    for token in expected_tokens:
        assert token in source


def test_campaign_workspace_source_has_guided_next_step_action() -> None:
    assert_campaign_next_step_contract(frontend_source())


def test_built_esp_bundle_includes_campaign_guided_next_step_action() -> None:
    bundle = frontend_bundle()
    expected_tokens = [
        'Guided next step',
        'Run readiness',
        'Fix validation blockers',
        'Preview test content',
        'Dry-run launch',
        'Dry-run result',
        'Launch result',
        'Test send result',
        'Refresh Readiness',
        'Check Audience',
        'Preview Email',
        'Dry-Run Launch',
        'Open delivery',
        'Campaign triage',
        'Create campaign draft',
        'Choose template',
        'Choose audience',
        'Send proof email',
        'Monitor delivery',
        'Campaign ready',
        'Proof and launch',
        'Launch Foundations',
        'Template contract',
        'Audience snapshot',
        'Send engine handoff',
        'Suppression impact',
        'AI Campaign Review',
        'Run AI Review',
        'No AI campaign review loaded',
        'Run AI Campaign Review after loading readiness',
    ]

    for token in expected_tokens:
        assert token in bundle
