from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FRONTEND_SOURCE = ROOT / 'frontend' / 'src' / 'main.tsx'
FRONTEND_DIST = ROOT / 'frontend' / 'dist'


def frontend_source() -> str:
    return FRONTEND_SOURCE.read_text()


def frontend_bundle() -> str:
    assets = sorted((FRONTEND_DIST / 'assets').glob('index-*.js'))
    assert assets, 'frontend/dist does not include the built ESP index bundle'
    return '\n'.join(asset.read_text() for asset in assets)


def assert_delivery_triage_contract(source: str) -> None:
    expected_tokens = [
        'deliveryTriageAction',
        'deliveryTriageItems',
        "title: 'Review failed records'",
        "title: 'Process queued delivery'",
        "title: 'Load job progress'",
        "title: 'Delivery clear'",
        'Delivery triage',
        'Queue pressure',
        'Failure review',
        'Selected job',
        'Selected record',
        'providerFootprint',
        'deliveryFoundationItems',
        'Send Engine Foundation',
        'Managed MTA nodes',
        'Load deployment summary or apply a provider profile to populate MTA inventory.',
        'Send queues',
        'Bounce queues',
        'No failed-record bounce signals in the loaded list.',
        'Deliverability feedback',
        'Provider events and managed-MTA feedback are normalized into one delivery evidence stream.',
        'deliveryOperationsContractItems',
        'Send Engine Operations Contract',
        'Operational contracts for managed MTA routing, queue lifecycle, retries, bounces, feedback, and deliverability controls.',
        'SMTP service contract',
        'Apply the Scaleway profile or load deployment summary to inspect managed-MTA route coverage.',
        'Queue lifecycle',
        'Send queues need claim locks, visibility timeouts, dead-letter handling, and operator-safe replay controls.',
        'Queue audit',
        'claim-blocked audit row(s)',
        'delivery-audit-panel',
        'delivery-audit-list',
        'Delivery Attempt Audit',
        'Load Attempt Audit',
        'Dead-letter Record',
        '/api/v1/delivery-attempts/list',
        '/api/v1/email-send-records/${selectedRecordId}/dead-letter',
        'ProviderFeedbackEventRead',
        'ManagedSmtpReadinessCheckRead',
        'ManagedSmtpDeploymentSummaryRead',
        'ManagedSmtpFirstSendRead',
        'MtaNodeEventRead',
        'providerFeedbackEvents',
        'providerFeedbackTotal',
        'mtaNodeEvents',
        'mtaNodeEventTotal',
        'mtaNodeEventFilters',
        'managedSmtpDeploymentSummary',
        'managedSmtpDeploymentItems',
        'managedSmtpFleetItems',
        'delivery-score-strip',
        'Managed SMTP deployment score strip',
        'Managed SMTP fleet health strip',
        'fleet_health',
        'platform_code_revision',
        'platform_code_revision_label',
        'Fleet status',
        'Route-ready nodes',
        'Node status',
        'operational_ok_nodes',
        'operational_warning_nodes',
        'operational_blocked_nodes',
        'Next actions',
        'operator_next_action_counts',
        'operator_next_action_label_counts',
        'primary_next_action_code',
        'primary_next_action_label',
        'primary_next_action_count',
        'primary_next_action_summary',
        'primary_next_action_tone',
        'action_required',
        'Agent coverage',
        'Platform revision',
        'Host updates',
        'Agent systemd',
        'Load deployment summary for MTA agent systemd status.',
        'missing revision',
        'config drift',
        'agent_log_bounce_nodes',
        'agent_log_deferred_nodes',
        'agent_log_warning_nodes',
        'Postfix logs',
        'Load deployment summary for recent Postfix log health.',
        'Queue pressure',
        'Deferred queue',
        'Load deployment summary for deferred queue status.',
        'Provider blockers',
        'provider_port25_blocked_count',
        'provider_rdns_blocked_count',
        'provider_inactive_count',
        'submission_credentials_configured',
        'node_endpoint_label',
        'submission_endpoint_label',
        'pool_membership_label',
        'provider_blockers',
        'provider_blocker_labels',
        'provider blockers',
        'operator_next_action_code',
        'operator_next_action_code_label',
        'operator_next_action',
        'operator_next_action_tone',
        'routeRecordId',
        'routeAttemptId',
        'focusedDeliveryAttempt',
        'deliveryAttemptAuditLabel',
        'deliveryAttemptAuditButtonLabel',
        'Load linked audit',
        'deliveryAttemptEmptyTitle',
        'No linked delivery attempts visible',
        'deliveryAttemptEmptyDetail',
        'proof-send submission evidence',
        'Focused attempt',
        'load the linked record audit',
        'isFocusedAttempt',
        'Focused delivery record',
        'refreshDeliveryAttempts().catch',
        'routeBlockReason',
        'smtpReason',
        'smtpResponse',
        'metadata.smtp_response',
        'attemptHasIssue',
        'attemptCompletedOk',
        'mtaHost',
        'submissionProvider',
        '<dt>submission</dt>',
        'smtpCode',
        'dkimSelector',
        'envelopeFrom',
        'action code',
        'Resolve provider blocker(s):',
        'readiness_summary_label',
        'formatManagedSmtpProviderBlocker',
        'Port 25 blocked',
        'rDNS blocked',
        'Provider inactive',
        'agent_heartbeat_status',
        'agent_heartbeat_status_label',
        'agent_operational_status',
        'agent_operational_status_label',
        'agent_last_heartbeat_label',
        'agent_heartbeat_age_seconds',
        'agent_heartbeat_stale_after_seconds',
        'agent_queue_depth',
        'agent_deferred_count',
        'agent_active_count',
        'agent_queue_status',
        'agent_queue_status_label',
        'agent_queue_samples',
        'Queue samples',
        'No queue samples reported by the MTA agent.',
        'agent_log_samples',
        'agent_log_issue_status',
        'agent_log_issue_status_label',
        'managedSmtpNodeHasLogIssue',
        'recent logs',
        'Review recent Postfix log samples and resolve delivery issues before increasing volume.',
        'Postfix log samples',
        'No Postfix log samples reported by the MTA agent.',
        'platform_config_version',
        'agent_config_version',
        'agent_applied_config_version',
        'agent_config_in_sync',
        'agent_config_sync_label',
        'agent_service_active_state',
        'agent_service_sub_state',
        'agent_service_state_label',
        'agent_timer_active_state',
        'agent_timer_sub_state',
        'agent_timer_state_label',
        'agent_timer_next_elapse',
        'agent_code_revision',
        'agent_code_dirty',
        'agent_code_revision_label',
        'agent_host_update_required',
        'agent_host_update_status',
        'agent_host_update_status_label',
        'agent_host_update_detail',
        'host update',
        'host update status',
        'host update detail',
        'managedSmtpNodeAgentServiceFailed',
        'managedSmtpNodeAgentTimerUnhealthy',
        'managedSmtpNodeHasDeferredQueue',
        'agent service',
        'agent timer',
        'code_missing_nodes',
        'code_dirty_nodes',
        'code_outdated_nodes',
        'host_update_required_nodes',
        'host update',
        'agent_service_failed_nodes',
        'agent_timer_unhealthy_nodes',
        'service failed',
        'timer unhealthy',
        'config_drift_nodes',
        'agent heartbeat',
        'node status',
        'runtime config',
        'Runtime config evidence',
        'platform version',
        'agent reported',
        'agent applied',
        'last heartbeat',
        'service state',
        'timer state',
        'timer next run',
        'expected host revision',
        'host revision',
        'revision_missing',
        'dirty',
        'outdated',
        'managedSmtpNodeNextAction',
        'next action',
        'Restart or manually run the MTA agent on the host, then reload deployment summary.',
        'Restart the MTA agent service and inspect the service journal before routing traffic.',
        'Restart the MTA agent timer so recurring heartbeat and config checks continue.',
        'Resolve the host working-tree changes before using this MTA for production traffic.',
        'Run the host update workflow so this MTA pulls the deployed platform revision.',
        'Run the host update workflow so this MTA reports its code revision.',
        'Run the MTA agent once so it fetches and applies the latest runtime config.',
        'Run managed SMTP readiness smoke and publish the result before routing traffic.',
        'Inspect the MTA mail queue and resolve deferred delivery before increasing volume.',
        'No operator action required for this MTA node.',
        'managedSmtpAgentCommands',
        'managedSmtpHostUpdateCommands',
        'Host agent commands',
        'Host update workflow',
        'cd /root/apps/email-engine',
        'git pull --ff-only',
        'python3 -m py_compile scripts/managed_smtp_mta_agent.py',
        'sudo systemctl restart email-engine-mta-agent.timer',
        '# Then click Load SMTP Deployment and confirm host update returns not required.',
        'service state',
        'timer state',
        'sudo systemctl start email-engine-mta-agent.service',
        'sudo systemctl status email-engine-mta-agent.service --no-pager',
        'sudo systemctl list-timers email-engine-mta-agent.timer',
        'sudo journalctl -u email-engine-mta-agent.service -n 80 --no-pager',
        'Submission auth',
        'worker-to-MTA submission',
        'readinessChecks',
        'readinessCheckTotal',
        'readinessSummary',
        'readinessTrend',
        'readinessAlerts',
        'readinessNotification',
        'readinessFilters',
        'alert_status',
        'alert_reasons',
        'alert_checks',
        'alert_count',
        'should_notify',
        'dedupe_key',
        'feedbackFilters',
        'providerFeedbackWarningCount',
        'readinessWarningCount',
        'latestReadinessCheck',
        'latestSuccessfulReadiness',
        'Managed SMTP Readiness',
        'readiness-status-strip',
        'readiness-status-item',
        'Managed SMTP readiness status strip',
        'Managed SMTP Deployment',
        'Managed SMTP deployment score strip',
        'Managed SMTP First Send',
        'Go/no-go checklist for the first controlled seed email through the owned MTA path.',
        'First-send status',
        'Evidence required before next seed send',
        'Ready for controlled seed send',
        'firstSendSummaryDetail',
        'firstSendControlProgress',
        'created_at',
        'Provider port 25',
        'Load or apply a live provider profile; AWS can remain pending while Scaleway handles seed sends.',
        'PTR/rDNS',
        'Submission auth',
        'Domain auth',
        'MTA smoke',
        'Load First Send Evidence',
        'Load Readiness',
        'firstSendReadiness',
        'firstSendReadinessItems',
        'first-send-checklist',
        'first-send-check',
        'function loadFirstSendEvidence',
        '/api/v1/managed-smtp/first-send-readiness',
        'port25_status',
        'rdns_status',
        'node_status_label',
        'provider_account_status_label',
        'provider_port25_status_label',
        'provider_rdns_status_label',
        'support_case_ref',
        'support case',
        'port 25',
        'rDNS',
        'Control-plane inventory for provider accounts, MTA nodes, IP pools, routes, and node readiness.',
        'Load SMTP Deployment',
        'Pause MTA Node',
        'Resume MTA Node',
        'MTA node status change cancelled; reason is required.',
        'Operator pausing MTA node for delivery review',
        'Operator resuming MTA node after review',
        "operator: 'esp_admin'",
        'function setManagedSmtpNodeOperationalStatus',
        '/api/v1/managed-smtp/nodes/${node.id}/${action}',
        'Load MTA Events',
        'MTA Agent Telemetry',
        'Signed node events from managed MTA hosts',
        'Apply MTA Event Filters',
        'Clear MTA Event Filters',
        'No MTA agent telemetry loaded',
        'MTA event payload',
        'runtime_config_applied',
        'function loadMtaNodeEvents',
        'function updateMtaNodeEventFilter',
        '/api/v1/managed-smtp/node-events/list',
        'Submission auth',
        'No managed SMTP deployment summary loaded',
        'function loadManagedSmtpDeploymentSummary',
        '/api/v1/managed-smtp/deployment-summary',
        'Published MTA smoke, STARTTLS, DKIM, and feedback-loop checks',
        'Load SMTP Readiness',
        'Apply Readiness Filters',
        'Clear Readiness Filters',
        'Latest check',
        'Latest pass',
        'Passing checks',
        'Backend readiness summary across matching checks',
        'Recent trend',
        'Trend alert',
        'Alert evidence',
        'Notification payload',
        'Ready to notify',
        'Notification quiet',
        'Load readiness to prepare external alert payload.',
        'Load readiness to classify managed SMTP health.',
        'Window comparison',
        'Latest window failure rate versus previous window',
        'No managed SMTP readiness checks loaded',
        '/api/v1/managed-smtp/readiness-checks/list',
        '/api/v1/managed-smtp/readiness-checks/summary',
        '/api/v1/managed-smtp/readiness-checks/trend',
        '/api/v1/managed-smtp/readiness-checks/alerts',
        '/api/v1/managed-smtp/readiness-checks/notification',
        'function loadReadinessChecks',
        'function updateReadinessFilter',
        'Provider Feedback Evidence',
        'Retained raw provider and managed-SMTP feedback',
        'Load Provider Feedback',
        'Use Selected Record',
        'No provider feedback evidence loaded',
        'provider-feedback-panel',
        'provider-feedback-list',
        'provider-feedback-strip',
        'provider-feedback-strip-item',
        'Managed SMTP provider feedback strip',
        '/api/v1/provider-feedback-events/list',
        'function loadProviderFeedbackEvents',
        'function useSelectedRecordForFeedbackFilters',
        'managed_smtp_dsn_feedback',
        'dsn_bounce',
        'Retry policy',
        'Retries need provider-aware backoff, max-attempt policy, suppression checks, and permanent-failure promotion.',
        'Bounce classification',
        'Failures must classify hard bounce, soft bounce, complaint, deferral, and policy block outcomes.',
        'Feedback ingestion',
        'Provider events and managed-MTA logs feed one durable stream into suppression and analytics records.',
        'Deliverability controls',
        'Domain warmup, reputation monitoring, inbox-placement signals, and throttle overrides remain roadmap controls.',
        'domain-compliance-panel',
        'domain-compliance-strip',
        'domain-compliance-item',
        'Managed SMTP domain compliance strip',
        'Managed SMTP Domain Compliance',
        'Compliance hold, release, reputation dashboard, and policy audit controls for managed sending domains.',
        'Load Domain Policies',
        'Managed SMTP Route Resolution',
        'Resolve Route',
        'Resolve SMTP Route',
        'Decision',
        'Rule',
        'decision_basis',
        'routing_rule_name',
        'routing_rule_source',
        'preferred_providers',
        'provider_preference_mode',
        'fallback_allowed',
        'ip_pool_selection_source',
        'mta_node_candidate_count',
        'mta_node_skipped_count',
        'provider_port25_not_ready',
        'provider_rdns_not_ready',
        'Failover selection',
        'managedSmtpRouteSelection',
        'Route block details',
        'managedSmtpRouteResolution',
        'managedSmtpRouteItems',
        'managed-smtp-route-inspector',
        'managed-smtp-route-field',
        'Managed SMTP Routing Rules',
        'managedSmtpRoutingRuleForm',
        'managedSmtpRoutingRules',
        'conflicts',
        '<span>Conflict</span>',
        'Rule overlap',
        'managedSmtpRulePreview',
        'selectedManagedSmtpRoutingRuleName',
        'loadManagedSmtpRoutingRuleIntoForm',
        'function loadManagedSmtpRoutingRules',
        'function saveManagedSmtpRoutingRule',
        'function previewManagedSmtpRoutingRule',
        'function setSelectedManagedSmtpRoutingRuleEnabled',
        'function deleteSelectedManagedSmtpRoutingRule',
        '/api/v1/delivery-routes/${selectedDomainPolicy.route_id}/managed-smtp/routing-rules',
        '/${encodeURIComponent(ruleName)}/${enabled ? \'enable\' : \'disable\'}',
        'Delete Rule',
        'Disable Rule',
        'Enable Rule',
        'Preview Rule',
        'Previewing managed SMTP routing rule',
        'Preview resolved',
        'Preview blocked',
        'Save Routing Rule',
        'Load Rules',
        'ManagedSmtpRouteResolutionRead',
        'function resolveManagedSmtpRoute',
        '/api/v1/managed-smtp/resolve-route',
        'Load Reputation Dashboard',
        'Apply Compliance Hold',
        'Release Compliance Hold',
        'function loadDomainReputationDashboard',
        'function applyDomainComplianceHold',
        'function releaseDomainComplianceHold',
        '/api/v1/domain-delivery-policies/list',
        '/api/v1/domain-delivery-policies/${selectedDomainPolicyId}/reputation-dashboard',
        '/api/v1/domain-delivery-policies/${selectedDomainPolicyId}/compliance-hold',
        '/api/v1/domain-delivery-policies/${selectedDomainPolicyId}/release-compliance-hold',
        'delivery-foundation-panel',
        'delivery-foundation-strip',
        'delivery-foundation-item',
        'Send engine foundation strip',
        'delivery-operations-panel',
        'delivery-operations-checklist',
        'delivery-operations-check',
        'delivery-triage-panel',
        'delivery-triage-list',
        'delivery-triage-row',
        'Delivery triage support list',
        'aiDeliverySummary',
        'aiDeliveryRecommendations',
        'function reviewDeliveryWithAi',
        'function deleteRecord',
        '/api/v1/ai/delivery/analyze',
        '/api/v1/email-send-records/${selectedRecordId}',
        "method: 'DELETE'",
        'delivery_context',
        'AI Delivery Review',
        'Delete Record',
        'Dead-letter Record',
        'Delivery Attempt Audit',
        'Load Attempt Audit',
        'Run AI Review',
        'delivery-ai-review-panel',
        'delivery-ai-summary',
        'No AI delivery review loaded',
    ]

    for token in expected_tokens:
        assert token in source


def test_delivery_source_has_triage_panel() -> None:
    assert_delivery_triage_contract(frontend_source())


def test_built_esp_bundle_includes_delivery_triage_panel() -> None:
    bundle = frontend_bundle()
    expected_tokens = [
        'Delivery triage',
        'Review failed records',
        'Process queued delivery',
        'Load job progress',
        'Delivery clear',
        'Queue pressure',
        'Failure review',
        'Selected job',
        'Selected record',
        'Send Engine Foundation',
        'Managed MTA nodes',
        'Send queues',
        'Bounce queues',
        'Deliverability feedback',
        'Send Engine Operations Contract',
        'SMTP service contract',
        'Queue lifecycle',
        'Retry policy',
        'Bounce classification',
        'Feedback ingestion',
        'Deliverability controls',
        'Managed SMTP Domain Compliance',
        'Load Domain Policies',
        'Load Reputation Dashboard',
        'Apply Compliance Hold',
        'Release Compliance Hold',
        'Compliance audit',
        'Provider settings',
        'Open Compliance',
        'AI Delivery Review',
        'Delete Record',
        'Dead-letter Record',
        'Delivery Attempt Audit',
        'Load Attempt Audit',
        'Run AI Review',
        'Provider Feedback Evidence',
        'Managed SMTP Readiness',
        'Managed SMTP Deployment',
        'Fleet status',
        'Route-ready nodes',
        'Agent coverage',
        'Platform revision',
        'Host updates',
        'Agent systemd',
        'config drift',
        'Deferred queue',
        'Runtime config evidence',
        'next action',
        'Host agent commands',
        'Host update workflow',
        'git pull --ff-only',
        'host revision',
        'expected host revision',
        'revision_missing',
        'outdated',
        'Run the host update workflow so this MTA pulls the deployed platform revision.',
        'sudo systemctl start email-engine-mta-agent.service',
        '# Then click Load SMTP Deployment and confirm host update returns not required.',
        'Run the MTA agent once so it fetches and applies the latest runtime config.',
        'Queue pressure',
        'Provider blockers',
        'Pause MTA Node',
        'Resume MTA Node',
        'MTA Agent Telemetry',
        'Load MTA Events',
        'Apply MTA Event Filters',
        'Clear MTA Event Filters',
        'No MTA agent telemetry loaded',
        'runtime_config_applied',
        'Managed SMTP First Send',
        'First-send status',
        'Evidence required before next seed send',
        'Provider port 25',
        'Load or apply a live provider profile; AWS can remain pending while Scaleway handles seed sends.',
        'PTR/rDNS',
        'Domain auth',
        'MTA smoke',
        'Load First Send Evidence',
        'Load SMTP Deployment',
        'No managed SMTP deployment summary loaded',
        'support case',
        'port 25',
        'rDNS',
        'Load SMTP Readiness',
        'Apply Readiness Filters',
        'Clear Readiness Filters',
        'Trend alert',
        'Alert evidence',
        'Notification payload',
        'Ready to notify',
        'Notification quiet',
        'Load readiness to prepare external alert payload.',
        'Load readiness to classify managed SMTP health.',
        'No managed SMTP readiness checks loaded',
        'Load Provider Feedback',
        'Use Selected Record',
        'No provider feedback evidence loaded',
        'Retained raw provider and managed-SMTP feedback',
        '/api/v1/provider-feedback-events/list',
        'Load Profiles',
        'Apply Profile',
        'Profile applied',
        'Provider bootstrap profile',
        '/api/v1/managed-smtp/bootstrap-profiles/list',
        '/api/v1/managed-smtp/bootstrap-profiles/',
        '/api/v1/managed-smtp/deployment-summary',
        '/api/v1/managed-smtp/node-events/list',
        '/api/v1/managed-smtp/first-send-readiness',
        '/api/v1/managed-smtp/readiness-checks/list',
        '/api/v1/managed-smtp/readiness-checks/summary',
        '/api/v1/managed-smtp/readiness-checks/trend',
        '/api/v1/managed-smtp/readiness-checks/alerts',
        '/api/v1/managed-smtp/readiness-checks/notification',
        'managed_smtp_dsn_feedback',
        'dsn_bounce',
        '/api/v1/delivery-attempts/list',
        '/api/v1/delivery-attempts/evidence-summary',
        '/api/v1/delivery-attempts/evidence-export.csv',
        'Route Blocks',
        'Resolved Rule Hits',
        'Strict Provider Preference',
        'delivery attempt evidence preset.',
        'Apply Attempt Filters',
        'Clear Attempt Filters',
        'mta_route_resolved',
        'mta_route_send_type',
        'mta_route_sender_domain',
        'mta_route_recipient_domain',
        'mta_routing_rule_name',
        'mta_routing_rule_source',
        'mta_rule_hit_pool_source',
        'mta_rule_hit_provider_preference',
        'mta_route_block_code',
        'Active delivery attempt evidence filters',
        'Active evidence filters',
        'Remove filter',
        'Removed ',
        'Cleared delivery attempt evidence filters.',
        'Auto-refreshed delivery attempt evidence filters',
        'Delivery attempt evidence rollup',
        'Evidence Follow-Up',
        'Jump from route evidence into pool, rule, provider, and readiness controls.',
        'Inspect selected pool',
        'Focus Pool Controls',
        'Loaded evidence-matched pool controls',
        'Review matched rule',
        'Select Matched Rule',
        'Loaded and selected evidence-matched routing rule',
        'Validate provider path',
        'Resolve block evidence',
        'Matching evidence rows',
        'Export scope',
        'Export cap',
        'Full matching set fits within the CSV export cap.',
        'Copy Evidence Pack',
        'Delivery Attempt Evidence Pack',
        'Copied delivery attempt evidence pack',
        'Export Evidence CSV',
        'delivery-attempt-evidence-',
        'scope and truncation metadata',
        'Top route provider',
        'Top route pool',
        'Top routing rule',
        'Top send type',
        'Top sender domain',
        'Top recipient domain',
        'Top rule source',
        'Top pool source',
        'Top block code',
        'rule source',
        'pool source',
        '/api/v1/ai/delivery/analyze',
        'No AI delivery review loaded',
    ]

    for token in expected_tokens:
        assert token in bundle
