from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FRONTEND_SOURCE = ROOT / 'frontend' / 'src' / 'main.tsx'
FRONTEND_DIST = ROOT / 'frontend' / 'dist'


def frontend_source() -> str:
    return FRONTEND_SOURCE.read_text()


def frontend_bundle() -> str:
    assets = sorted((FRONTEND_DIST / 'assets').glob('index-*.js'))
    assert assets, 'frontend/dist does not include the built ESP index bundle'
    return '\n'.join(asset.read_text() for asset in assets)


def assert_delivery_triage_contract(source: str) -> None:
    expected_tokens = [
        'deliveryTriageAction',
        'deliveryTriageItems',
        "title: 'Review failed records'",
        "title: 'Process queued delivery'",
        "title: 'Load job progress'",
        "title: 'Delivery clear'",
        'Delivery triage',
        'Queue pressure',
        'Failure review',
        'Selected job',
        'Selected record',
        'providerFootprint',
        'deliveryFoundationItems',
        'Send Engine Foundation',
        'Owned SMTP server',
        'Platform-owned SMTP service still needs MTA, auth, throttling, and domain controls.',
        'Send queues',
        'Bounce queues',
        'Dedicated bounce and complaint queues are still needed.',
        'Deliverability feedback',
        'Reputation, complaint, bounce, and inbox-placement feedback need a unified loop.',
        'deliveryOperationsContractItems',
        'Send Engine Operations Contract',
        'Operational contracts for owned SMTP, queue lifecycle, retries, bounces, feedback, and deliverability controls.',
        'SMTP service contract',
        'Owned SMTP needs MTA configuration, authenticated submission, domain policy, TLS, and tenant-level rate controls.',
        'Queue lifecycle',
        'Send queues need claim locks, visibility timeouts, dead-letter handling, and operator-safe replay controls.',
        'Queue audit',
        'claim-blocked audit row(s)',
        'delivery-audit-panel',
        'delivery-audit-list',
        'Delivery Attempt Audit',
        'Load Attempt Audit',
        'Dead-letter Record',
        '/api/v1/delivery-attempts/list',
        '/api/v1/email-send-records/${selectedRecordId}/dead-letter',
        'ProviderFeedbackEventRead',
        'ManagedSmtpReadinessCheckRead',
        'ManagedSmtpDeploymentSummaryRead',
        'ManagedSmtpFirstSendRead',
        'providerFeedbackEvents',
        'providerFeedbackTotal',
        'managedSmtpDeploymentSummary',
        'managedSmtpDeploymentItems',
        'delivery-score-strip',
        'Managed SMTP deployment score strip',
        'submission_credentials_configured',
        'Submission auth',
        'worker-to-MTA submission',
        'readinessChecks',
        'readinessCheckTotal',
        'readinessSummary',
        'readinessTrend',
        'readinessAlerts',
        'readinessNotification',
        'readinessFilters',
        'alert_status',
        'alert_reasons',
        'alert_checks',
        'alert_count',
        'should_notify',
        'dedupe_key',
        'feedbackFilters',
        'providerFeedbackWarningCount',
        'readinessWarningCount',
        'latestReadinessCheck',
        'latestSuccessfulReadiness',
        'Managed SMTP Readiness',
        'Managed SMTP Deployment',
        'Managed SMTP deployment score strip',
        'Managed SMTP First Send',
        'Go/no-go checklist for the first controlled seed email through the owned MTA path.',
        'First-send status',
        'First seed send blocked',
        'Ready for first seed send',
        'firstSendSummaryDetail',
        'firstSendControlProgress',
        'created_at',
        'AWS port 25',
        'Seed send remains blocked until the provider removes outbound TCP 25 limits.',
        'PTR/rDNS',
        'Submission auth',
        'Domain auth',
        'MTA smoke',
        'Load First Send Evidence',
        'Load Readiness',
        'firstSendReadiness',
        'firstSendReadinessItems',
        'first-send-checklist',
        'first-send-check',
        'function loadFirstSendEvidence',
        '/api/v1/managed-smtp/first-send-readiness',
        'port25_status',
        'rdns_status',
        'support_case_ref',
        'support case',
        'port 25',
        'rDNS',
        'Control-plane inventory for provider accounts, MTA nodes, IP pools, routes, and node readiness.',
        'Load SMTP Deployment',
        'Submission auth',
        'No managed SMTP deployment summary loaded',
        'function loadManagedSmtpDeploymentSummary',
        '/api/v1/managed-smtp/deployment-summary',
        'Published MTA smoke, STARTTLS, DKIM, and feedback-loop checks',
        'Load SMTP Readiness',
        'Apply Readiness Filters',
        'Clear Readiness Filters',
        'Latest check',
        'Latest pass',
        'Passing checks',
        'Backend readiness summary across matching checks',
        'Recent trend',
        'Trend alert',
        'Alert evidence',
        'Notification payload',
        'Ready to notify',
        'Notification quiet',
        'Load readiness to prepare external alert payload.',
        'Load readiness to classify managed SMTP health.',
        'Window comparison',
        'Latest window failure rate versus previous window',
        'No managed SMTP readiness checks loaded',
        '/api/v1/managed-smtp/readiness-checks/list',
        '/api/v1/managed-smtp/readiness-checks/summary',
        '/api/v1/managed-smtp/readiness-checks/trend',
        '/api/v1/managed-smtp/readiness-checks/alerts',
        '/api/v1/managed-smtp/readiness-checks/notification',
        'function loadReadinessChecks',
        'function updateReadinessFilter',
        'Provider Feedback Evidence',
        'Retained raw provider and managed-SMTP feedback',
        'Load Provider Feedback',
        'Use Selected Record',
        'No provider feedback evidence loaded',
        'provider-feedback-panel',
        'provider-feedback-list',
        '/api/v1/provider-feedback-events/list',
        'function loadProviderFeedbackEvents',
        'function useSelectedRecordForFeedbackFilters',
        'managed_smtp_dsn_feedback',
        'dsn_bounce',
        'Retry policy',
        'Retries need provider-aware backoff, max-attempt policy, suppression checks, and permanent-failure promotion.',
        'Bounce classification',
        'Failures must classify hard bounce, soft bounce, complaint, deferral, and policy block outcomes.',
        'Feedback ingestion',
        'Provider events and owned SMTP logs need one durable feedback stream into suppression and analytics records.',
        'Deliverability controls',
        'Domain warmup, reputation monitoring, inbox-placement signals, and throttle overrides need admin controls.',
        'domain-compliance-panel',
        'domain-compliance-strip',
        'domain-compliance-item',
        'Managed SMTP domain compliance strip',
        'Managed SMTP Domain Compliance',
        'Compliance hold, release, reputation dashboard, and policy audit controls for owned SMTP domains.',
        'Load Domain Policies',
        'Managed SMTP Route Resolution',
        'Resolve Route',
        'Resolve SMTP Route',
        'Route block details',
        'managedSmtpRouteResolution',
        'managedSmtpRouteItems',
        'managed-smtp-route-inspector',
        'managed-smtp-route-field',
        'ManagedSmtpRouteResolutionRead',
        'function resolveManagedSmtpRoute',
        '/api/v1/managed-smtp/resolve-route',
        'Load Reputation Dashboard',
        'Apply Compliance Hold',
        'Release Compliance Hold',
        'function loadDomainReputationDashboard',
        'function applyDomainComplianceHold',
        'function releaseDomainComplianceHold',
        '/api/v1/domain-delivery-policies/list',
        '/api/v1/domain-delivery-policies/${selectedDomainPolicyId}/reputation-dashboard',
        '/api/v1/domain-delivery-policies/${selectedDomainPolicyId}/compliance-hold',
        '/api/v1/domain-delivery-policies/${selectedDomainPolicyId}/release-compliance-hold',
        'delivery-foundation-panel',
        'delivery-foundation-grid',
        'delivery-operations-panel',
        'delivery-operations-checklist',
        'delivery-operations-check',
        'delivery-triage-panel',
        'delivery-triage-grid',
        'aiDeliverySummary',
        'aiDeliveryRecommendations',
        'function reviewDeliveryWithAi',
        'function deleteRecord',
        '/api/v1/ai/delivery/analyze',
        '/api/v1/email-send-records/${selectedRecordId}',
        "method: 'DELETE'",
        'delivery_context',
        'AI Delivery Review',
        'Delete Record',
        'Dead-letter Record',
        'Delivery Attempt Audit',
        'Load Attempt Audit',
        'Run AI Review',
        'delivery-ai-review-panel',
        'delivery-ai-summary',
        'No AI delivery review loaded',
    ]

    for token in expected_tokens:
        assert token in source


def test_delivery_source_has_triage_panel() -> None:
    assert_delivery_triage_contract(frontend_source())


def test_built_esp_bundle_includes_delivery_triage_panel() -> None:
    bundle = frontend_bundle()
    expected_tokens = [
        'Delivery triage',
        'Review failed records',
        'Process queued delivery',
        'Load job progress',
        'Delivery clear',
        'Queue pressure',
        'Failure review',
        'Selected job',
        'Selected record',
        'Send Engine Foundation',
        'Owned SMTP server',
        'Send queues',
        'Bounce queues',
        'Deliverability feedback',
        'Send Engine Operations Contract',
        'SMTP service contract',
        'Queue lifecycle',
        'Retry policy',
        'Bounce classification',
        'Feedback ingestion',
        'Deliverability controls',
        'Managed SMTP Domain Compliance',
        'Load Domain Policies',
        'Load Reputation Dashboard',
        'Apply Compliance Hold',
        'Release Compliance Hold',
        'Compliance audit',
        'Provider settings',
        'Open Compliance',
        'AI Delivery Review',
        'Delete Record',
        'Dead-letter Record',
        'Delivery Attempt Audit',
        'Load Attempt Audit',
        'Run AI Review',
        'Provider Feedback Evidence',
        'Managed SMTP Readiness',
        'Managed SMTP Deployment',
        'Managed SMTP First Send',
        'First-send status',
        'First seed send blocked',
        'AWS port 25',
        'Seed send remains blocked until the provider removes outbound TCP 25 limits.',
        'PTR/rDNS',
        'Domain auth',
        'MTA smoke',
        'Load First Send Evidence',
        'Load SMTP Deployment',
        'No managed SMTP deployment summary loaded',
        'support case',
        'port 25',
        'rDNS',
        'Load SMTP Readiness',
        'Apply Readiness Filters',
        'Clear Readiness Filters',
        'Trend alert',
        'Alert evidence',
        'Notification payload',
        'Ready to notify',
        'Notification quiet',
        'Load readiness to prepare external alert payload.',
        'Load readiness to classify managed SMTP health.',
        'No managed SMTP readiness checks loaded',
        'Load Provider Feedback',
        'Use Selected Record',
        'No provider feedback evidence loaded',
        'Retained raw provider and managed-SMTP feedback',
        '/api/v1/provider-feedback-events/list',
        '/api/v1/managed-smtp/deployment-summary',
        '/api/v1/managed-smtp/first-send-readiness',
        '/api/v1/managed-smtp/readiness-checks/list',
        '/api/v1/managed-smtp/readiness-checks/summary',
        '/api/v1/managed-smtp/readiness-checks/trend',
        '/api/v1/managed-smtp/readiness-checks/alerts',
        '/api/v1/managed-smtp/readiness-checks/notification',
        'managed_smtp_dsn_feedback',
        'dsn_bounce',
        '/api/v1/delivery-attempts/list',
        '/api/v1/ai/delivery/analyze',
        'No AI delivery review loaded',
    ]

    for token in expected_tokens:
        assert token in bundle
